Resources:
  baseUrlsTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.baseUrlsTableName}
      AttributeDefinitions:
        - AttributeName: baseUrl
          AttributeType: S
      KeySchema:
        - AttributeName: baseUrl
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1