Resources:
  listingsTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.listingsTableName}
      AttributeDefinitions:
        - AttributeName: url
          AttributeType: S
      KeySchema:
        - AttributeName: url
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 24
        WriteCapacityUnits: 24