service: realstate-scraper
app: realstate
org: jhonorato

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage}
  region: us-east-1
  profile: mathetes
  
  memorySize: 256
  timeout: 900
  
  environment:
    baseUrlsTableName: baseUrlsTable
    listingsTableName: listingsTable

functions:
  getNewListings:
    handler: new_listings.get_new_listings

    events:
      - schedule: rate(60 minutes)

resources:
  # Create base Urls table
  - ${file(resources/baseUrls-table-create.yml)}
  # Create listings table
  - ${file(resources/listings-table-create.yml)}

package:
  exclude:
    - node_modules/**
    - serverless_sdk/**
    - .vscode/**
    - test/**


custom:
  pythonRequirements:
    dockerizePip: true

plugins:
  - serverless-python-requirements