service: realstate-scraper
app: realstate
org: jhonorato

provider:
	name: aws
	runtime: python3.8
	stage: dev
	region: us-east-1


environment:
	variable1: value1

functions:
  hello:
	handler: handler.hello

   events:
     - schedule: rate(60 minutes)
